WebFilm/Models/Film.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFilm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int FilmID { get; set; }
        public string Filmname { get; set; }
        public int AuthorID { get; set; }
        public int CategoryID { get; set; }
        public int GenreID { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<System.DateTime> ReleaseDay { get; set; }
        public Nullable<double> Rating { get; set; }
        public Nullable<int> CurrnentEpisodes { get; set; }
        public Nullable<int> Episodes { get; set; }
        public int CountryID { get; set; }
        public Nullable<bool> Status { get; set; }
        public string FilmPath { get; set; }
        public string Poster { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Country Country { get; set; }
        public virtual Genre Genre { get; set; }
    }
}

WebFilm/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebFilm.Models;

namespace WebFilm.Controllers
{
    public class AuthorsController : Controller
    {
        private WebXemPhimEntities db = new WebXemPhimEntities();

        // GET: Authors
        public ActionResult Index()
        {
            return View(db.Authors.ToList());
        }

        // GET: Authors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // GET: Authors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Authors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AuthorID,Fullname")] Author author)
        {
            if (ModelState.IsValid)
            {
                db.Authors.Add(author);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(author);
        }

        // GET: Authors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // POST: Authors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AuthorID,Fullname")] Author author)
        {
            if (ModelState.IsValid)
            {
                db.Entry(author).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(author);
        }

        // GET: Authors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Author author = db.Authors.Find(id);
            db.Authors.Remove(author);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebFilm/Controllers/FilmsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebFilm.Models;

namespace WebFilm.Controllers
{
    public class FilmsController : Controller
    {
        private WebXemPhimEntities db = new WebXemPhimEntities();

        // GET: Films
        public ActionResult Index()
        {
            var films = db.Films.Include(f => f.Author).Include(f => f.Category).Include(f => f.Country).Include(f => f.Genre);
            return View(films.ToList());
        }

        // GET: Films/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Film film = db.Films.Find(id);
            if (film == null)
            {
                return HttpNotFound();
            }
            return View(film);
        }

        // GET: Films/Create
        public ActionResult Create()
        {
            ViewBag.AuthorID = new SelectList(db.Authors, "AuthorID", "Fullname");
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Catename");
            ViewBag.CountryID = new SelectList(db.Countries, "CountryID", "Countryname");
            ViewBag.GenreID = new SelectList(db.Genres, "GenreID", "Genrename");
            return View();
        }

        // POST: Films/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FilmID,Filmname,AuthorID,CategoryID,GenreID,Length,ReleaseDay,Rating,CurrnentEpisodes,Episodes,CountryID,Status,FilmPath,Poster")] Film film)
        {
            film.CurrnentEpisodes = 1;
            film.Episodes = 1;
            if (ModelState.IsValid)
            {
                db.Films.Add(film);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AuthorID = new SelectList(db.Authors, "AuthorID", "Fullname", film.AuthorID);
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Catename", film.CategoryID);
            ViewBag.CountryID = new SelectList(db.Countries, "CountryID", "Countryname", film.CountryID);
            ViewBag.GenreID = new SelectList(db.Genres, "GenreID", "Genrename", film.GenreID);
            return View(film);
        }

        // GET: Films/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Film film = db.Films.Find(id);
            if (film == null)
            {
                return HttpNotFound();
            }
            ViewBag.AuthorID = new SelectList(db.Authors, "AuthorID", "Fullname", film.AuthorID);
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Catename", film.CategoryID);
            ViewBag.CountryID = new SelectList(db.Countries, "CountryID", "Countryname", film.CountryID);
            ViewBag.GenreID = new SelectList(db.Genres, "GenreID", "Genrename", film.GenreID);
            return View(film);
        }

        // POST: Films/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "FilmID,Filmname,AuthorID,CategoryID,GenreID,Length,ReleaseDay,Rating,CurrnentEpisodes,Episodes,CountryID,Status,FilmPath,Poster")] Film film)
        {
            film.CurrnentEpisodes = 1;
            film.Episodes = 1;
            if (ModelState.IsValid)
            {
                db.Entry(film).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AuthorID = new SelectList(db.Authors, "AuthorID", "Fullname", film.AuthorID);
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Catename", film.CategoryID);
            ViewBag.CountryID = new SelectList(db.Countries, "CountryID", "Countryname", film.CountryID);
            ViewBag.GenreID = new SelectList(db.Genres, "GenreID", "Genrename", film.GenreID);
            return View(film);
        }

        // GET: Films/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Film film = db.Films.Find(id);
            if (film == null)
            {
                return HttpNotFound();
            }
            return View(film);
        }

        // POST: Films/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Film film = db.Films.Find(id);
            db.Films.Remove(film);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebFilm/Controllers/GenresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebFilm.Models;

namespace WebFilm.Controllers
{
    public class GenresController : Controller
    {
        private WebXemPhimEntities db = new WebXemPhimEntities();

        // GET: Genres
        public ActionResult Index()
        {
            return View(db.Genres.ToList());
        }

        // GET: Genres/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Genre genre = db.Genres.Find(id);
            if (genre == null)
            {
                return HttpNotFound();
            }
            return View(genre);
        }

        // GET: Genres/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Genres/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "GenreID,Genrename")] Genre genre)
        {
            if (ModelState.IsValid)
            {
                db.Genres.Add(genre);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(genre);
        }

        // GET: Genres/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Genre genre = db.Genres.Find(id);
            if (genre == null)
            {
                return HttpNotFound();
            }
            return View(genre);
        }

        // POST: Genres/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "GenreID,Genrename")] Genre genre)
        {
            if (ModelState.IsValid)
            {
                db.Entry(genre).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(genre);
        }

        // GET: Genres/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Genre genre = db.Genres.Find(id);
            if (genre == null)
            {
                return HttpNotFound();
            }
            return View(genre);
        }

        // POST: Genres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Genre genre = db.Genres.Find(id);
            db.Genres.Remove(genre);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebFilm/Views/Films/Create.cshtml
@model WebFilm.Models.Film

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Film</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Filmname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Filmname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Filmname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AuthorID, "AuthorID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AuthorID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AuthorID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, "CategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GenreID, "GenreID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GenreID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GenreID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Length, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Length, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Length, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseDay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseDay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReleaseDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
            </div>
        </div>

         

        <div class="form-group">
            @Html.LabelFor(model => model.CountryID, "CountryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CountryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CountryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Status)
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FilmPath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FilmPath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FilmPath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Poster, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Poster, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Poster, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebFilm/Views/Films/Delete.cshtml
@model WebFilm.Models.Film

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Film</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Filmname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Filmname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Length)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Length)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CurrnentEpisodes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurrnentEpisodes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Episodes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Episodes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FilmPath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FilmPath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Poster)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Poster)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author.Fullname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author.Fullname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.Catename)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Catename)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country.Countryname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country.Countryname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre.Genrename)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre.Genrename)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebFilm/Views/Films/Details.cshtml
@model WebFilm.Models.Film

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Film</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Filmname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Filmname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Length)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Length)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CurrnentEpisodes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurrnentEpisodes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Episodes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Episodes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FilmPath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FilmPath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Poster)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Poster)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author.Fullname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author.Fullname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.Catename)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Catename)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country.Countryname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country.Countryname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre.Genrename)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre.Genrename)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.FilmID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebFilm/Views/Films/Index.cshtml
@model IEnumerable<WebFilm.Models.Film>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Quản lí film</h2>

<div class="row">
    <div class="col-md-3">
        <h2>Quản lý loại film</h2>
        <p>
            Quản lý các mục cho film VD:film bộ, film tập,...
        </p>
        <p><a class="btn btn-default" href="@Url.Action("Index", "Categories")">Vào trang &raquo;</a></p>
    </div>
    <div class="col-md-3">
        <h2>Quản lý kiểu film</h2>
        <p>
            Quản lý các tag kiểu film VD:film kinh dị, film cổ điển, film tình cảm,...
        </p>
        <p><a class="btn btn-default" href="@Url.Action("Index", "Genres")">Vào trang &raquo;</a></p>
    </div>
    <div class="col-md-3">
        <h2>Quản lý Nhà sản xuất</h2>
        <p>
            Quản lý nhà sản xuất
        </p>
        <p><a class="btn btn-default" href="@Url.Action("Index", "Authors")">Vào trang &raquo;</a></p>
    </div>
    <div class="col-md-3">
        <h2>Quản lý quốc gia</h2>
        <p>
            Quản lý quốc gia sản xuất ra film
        </p>
        <p><a class="btn btn-default" href="@Url.Action("Index", "Countries")">Vào trang &raquo;</a></p>
    </div>
</div>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Filmname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Length)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReleaseDay)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rating)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CurrnentEpisodes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Episodes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FilmPath)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Poster)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Author.Fullname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category.Catename)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Country.Countryname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Genre.Genrename)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Filmname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Length)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseDay)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CurrnentEpisodes)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Episodes)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FilmPath)
            </td>
            <td>
                <img src="@item.Poster" width="150" title="Cover" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author.Fullname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.Catename)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country.Countryname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre.Genrename)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.FilmID }) |
                @Html.ActionLink("Details", "Details", new { id = item.FilmID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.FilmID })
            </td>
        </tr>
    }

</table>