WebFilm/Controllers/FilmsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebFilm.Models;

namespace WebFilm.Controllers
{
    public class FilmsController : Controller
    {
        private WebXemPhimEntities db = new WebXemPhimEntities();

        // GET: Films
        public ActionResult Index()
        {
            var films = db.Films.Include(f => f.Author).Include(f => f.Category).Include(f => f.Country).Include(f => f.Genre);
            return View(films.ToList());
        }

        // GET: Films/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Film film = db.Films.Find(id);
            if (film == null)
            {
                return HttpNotFound();
            }
            return View(film);
        }

        // GET: Films/Create
        public ActionResult Create()
        {
            ViewBag.AuthorID = new SelectList(db.Authors, "AuthorID", "Fullname");
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Catename");
            ViewBag.CountryID = new SelectList(db.Countries, "CountryID", "Countryname");
            ViewBag.GenreID = new SelectList(db.Genres, "GenreID", "Genrename");
            return View();
        }

        // POST: Films/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FilmID,Filmname,AuthorID,CategoryID,GenreID,Length,ReleaseDay,Rating,CurrnentEpisodes,Episodes,CountryID,Status,FilmPath,Poster")] Film film)
        {
            film.CurrnentEpisodes = 1;
            film.Episodes = 1;
            if (ModelState.IsValid)
            {
                db.Films.Add(film);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AuthorID = new SelectList(db.Authors, "AuthorID", "Fullname", film.AuthorID);
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Catename", film.CategoryID);
            ViewBag.CountryID = new SelectList(db.Countries, "CountryID", "Countryname", film.CountryID);
            ViewBag.GenreID = new SelectList(db.Genres, "GenreID", "Genrename", film.GenreID);
            return View(film);
        }

        // GET: Films/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Film film = db.Films.Find(id);
            if (film == null)
            {
                return HttpNotFound();
            }
            ViewBag.AuthorID = new SelectList(db.Authors, "AuthorID", "Fullname", film.AuthorID);
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Catename", film.CategoryID);
            ViewBag.CountryID = new SelectList(db.Countries, "CountryID", "Countryname", film.CountryID);
            ViewBag.GenreID = new SelectList(db.Genres, "GenreID", "Genrename", film.GenreID);
            return View(film);
        }

        // POST: Films/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "FilmID,Filmname,AuthorID,CategoryID,GenreID,Length,ReleaseDay,Rating,CurrnentEpisodes,Episodes,CountryID,Status,FilmPath,Poster")] Film film)
        {
            film.CurrnentEpisodes = 1;
            film.Episodes = 1;
            if (ModelState.IsValid)
            {
                db.Entry(film).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AuthorID = new SelectList(db.Authors, "AuthorID", "Fullname", film.AuthorID);
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Catename", film.CategoryID);
            ViewBag.CountryID = new SelectList(db.Countries, "CountryID", "Countryname", film.CountryID);
            ViewBag.GenreID = new SelectList(db.Genres, "GenreID", "Genrename", film.GenreID);
            return View(film);
        }

        // GET: Films/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Film film = db.Films.Find(id);
            if (film == null)
            {
                return HttpNotFound();
            }
            return View(film);
        }

        // POST: Films/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Film film = db.Films.Find(id);
            db.Films.Remove(film);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebFilm/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebFilm.Models;
namespace WebFilm.Controllers
{
    public class LoginController : Controller
    {
        private WebXemPhimEntities db = new WebXemPhimEntities();
        // GET: Login
        
        public ActionResult Index()
        {
            if (Session["username"] != "" && Session["username"] != null)
            {
                var films = db.Films.Include(f => f.Author).Include(f => f.Category).Include(f => f.Country).Include(f => f.Genre);
                var genres = from c in db.Genres select c;
                ViewBag.genres = genres.ToList();
                ViewBag.genresID = new SelectList(genres, "GenreID", "Genrename");
                ViewBag.genres = genres.ToList();
                return Redirect(Url.Action("Index", "Home", films.ToList()));
            }
            else 
            return View();
        }
        
        [HttpPost]
        public ActionResult Index(string username, string password)
        {
            Session["Timkiem"] = "-1";
            var histories = from c in db.Histories select c;
            ViewBag.history = histories.ToList();
            Double sotien = 0;
            for (int i = 1; i <= histories.Count(); i++)
            {
                var item = histories.FirstOrDefault(x => x.HistoryID == i);
                if (item != null)
                    sotien += (double)item.Money;
            }
            Session["Gain"] = sotien;
            var users = from d in db.Users select d;
            var listt = users.ToArray();
            int dem = 0;
            for (int i = 1; i <= listt.Length; i++)
            {
                var tmp = db.Histories.FirstOrDefault(x => x.UserID == i);
                if (tmp != null) dem++;
            }
            Session["NumBuy"] = dem;
            Session["Numdont"] = listt.Length - dem;
            Session["Percent"] = (float)dem / listt.Length * 100;
            //var histories = from c in db.Histories select c;
            ViewBag.history = histories.ToList();
            var userr = from s in db.Users select s;
            userr = userr.Where(s => s.Username.CompareTo(username) == 0);
            foreach (var item in userr)
            {
                if (item.Password.CompareTo(password) == 0)
                {
                    var categories = from c in db.Categories select c;
                    ViewBag.categoryID = new SelectList(categories, "CategoryID", "CategoryName");
                    Session["username"] = item.Username;
                    Session["accountname"] = item.Fullname;
                    Session["role"] = item.Status;
                    Session["userid"] = item.ID;
                    
                    Session["Able"] = "1";
                    ViewBag.error = "Good";
                    if (item.Status == false)
                    {
                        var films = db.Films.Include(f => f.Author).Include(f => f.Category).Include(f => f.Country).Include(f => f.Genre);
                        var genres = from c in db.Genres select c;
                        ViewBag.genres = genres.ToList();
                        ViewBag.genresID = new SelectList(genres, "GenreID", "Genrename");
                        ViewBag.genres = genres.ToList();
                         
                        return Redirect(Url.Action("Index", "Home", films.ToList())); }
                    else if (item.Status == true)
                        return Redirect(Url.Action("Dashboard", "Home" ));
                    else
                    {
                        var films = db.Films.Include(f => f.Author).Include(f => f.Category).Include(f => f.Country).Include(f => f.Genre);
                        var genres = from c in db.Genres select c;
                        ViewBag.genres = genres.ToList();
                        ViewBag.genresID = new SelectList(genres, "GenreID", "Genrename");
                        ViewBag.genres = genres.ToList();
                        return Redirect(Url.Action("Index", "Home", films.ToList()));
                    }
                }
            }
            Session["username"] = "";
            ViewBag.error = "Tên đăng nhập hoặc mật khẩu không hợp lệ";
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Logout()
        {
            Session.Remove("username"); Session.Remove("role"); Session.Remove("userid"); Session.Remove("accountname");
            return RedirectToAction("Index");
        }
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Username,Password,Fullname,Email,Phone,Address,Status")] User user, string password)
        {
            
            user.Status = false;
            if (ModelState.IsValid && password.CompareTo(user.Password)==0)
            {
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            if(password.CompareTo(user.Password) == 0) ViewBag.fail = "Nhập lại mật khẩu sai";
            ViewBag.error = "That bai";
            return View(user);
        }
    }
}

WebFilm/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebFilm.Models;

namespace WebFilm.Controllers
{
    public class UsersController : Controller
    {
        private WebXemPhimEntities db = new WebXemPhimEntities();

        // GET: Users
        public ActionResult Index()
        {
            return View(db.Users.ToList());
        }

        // GET: Users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Username,Password,Fullname,Email,Phone,Address,Status")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Username,Password,Fullname,Email,Phone,Address,Status")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebFilm/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <meta http-equiv="refresh" content="3; URL="" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebFilm/Views/Shared/_LayoutAdmin.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard - SB Admin</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
    <link href="/Assets/admin/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->

        <a class="navbar-brand ps-3" href="@Url.Action("Index", "Home")">BondHub</a>

        @if (Session["username"] != "" && Session["username"] != null)
        {
            if (Session["role"].ToString().CompareTo("True") == 0)
            {
                <!-- Sidebar Toggle-->
                <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            }

            <a class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="@Url.Action("Index", "Home")">Trang chủ</a>
            <a class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="/Home/IndexGenre">Thể loại film</a>
            <a class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="/Home/IndexCategory">Mục film</a>

            <!-- Navbar Search-->
           
            <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0" action="/Home/Index" method="post">
                <div class="input-group">
                    @Html.TextBox("SearchString", "", new { @class = "form-control" , @placeholder = "Search for...", aria_label = "Search for...", aria_describedby = "btnNavbarSearch" })
                    
                    <button class="btn btn-primary" id="btnNavbarSearch" type="submit" ><i class="fas fa-search"></i></button>
                </div>
            </form>
            <!-- Navbar-->
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="@Url.Action("Payment", "Home")">Mua gói</a></li>
                        <li><a class="dropdown-item" href="/UserVouchers/DetailsUser/@Session["userid"]">Voucher đang có</a></li>
                        <li><a class="dropdown-item" href="/Home/DetailsUser/@Session["userid"]">Thông tin người dùng</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="@Url.Action("Logout", "Login")">Logout</a></li>
                    </ul>
                </li>
            </ul>
        }

    </nav>

    @if (Session["username"] != "" && Session["username"] != null)
    {
        if (Session["role"].ToString().CompareTo("True") == 0)
        {
            <div id="layoutSidenav">
                <div id="layoutSidenav_nav">
                    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                        <div class="sb-sidenav-menu">
                            <div class="nav">
                                <div class="sb-sidenav-menu-heading">Main</div>
                                <a class="nav-link" href="@Url.Action("Dashboard", "Home")">
                                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                    Dashboard
                                </a>
                                <div class="sb-sidenav-menu-heading"> Quản lý người dùng chức năng</div>
                                <!--Quản lý Voucher-->
                                <a class="nav-link collapsed" href="@Url.Action("Index", "Vouchers")">

                                    Quản lí Voucher
                                </a>
                                <!--Quản lý thông tin người dùng-->
                                <a class="nav-link collapsed" href="@Url.Action("Index", "Users")">

                                    Quản lí thông tin người dùng
                                </a>

                                <div class="sb-sidenav-menu-heading">Quản lý sản phẩm</div>
                                <!--Quản lý đơn hàng-->
                                <a class="nav-link collapsed" href="@Url.Action("Index", "Packets")">

                                    Quản lí gói film
                                </a>
                                <a class="nav-link collapsed" href="@Url.Action("Index", "Histories")">

                                    Quản lí đơn hàng
                                </a>
                                <!--Quản lý Quản lý thông tin hàng hóa-->
                                <a class="nav-link collapsed" href="@Url.Action("Index", "Films")">

                                    Quản lí film
                                </a>
                                <!--Quản lý Quảng cáo-->
                                <a class="nav-link collapsed" href="@Url.Action("Index", "Advertises")">

                                    Quản lí Quảng cáo
                                </a>
                            </div>
                        </div>
                        <div class="sb-sidenav-footer">
                            <div class="small">Đã đăng nhập với tên:</div>
                            @Session["username"]
                        </div>
                    </nav>
                </div>
                <div id="layoutSidenav_content">
                    @RenderBody();
                    <footer class="py-4 bg-light mt-auto">
                        <div class="container-fluid px-4">
                            <div class="d-flex align-items-center justify-content-between small">
                                <div class="text-muted">Copyright &copy; Your Website 2022</div>
                                <div>
                                    <a href="#">Privacy Policy</a>
                                    &middot;
                                    <a href="#">Terms &amp; Conditions</a>
                                </div>
                            </div>
                        </div>
                    </footer>
                </div>
            </div>
        }
        else
        {
            <div id="layoutSidenav_content">
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2022</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
            @RenderBody();
        }
    }
    else
    { <div id="layoutSidenav_content">
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2022</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
        @RenderBody();
    }

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="/Assets/admin/js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="/Assets/admin/assets/demo/chart-area-demo.js"></script>
    <script src="/Assets/admin/assets/demo/chart-bar-demo.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
    <script src="/Assets/admin/js/datatables-simple-demo.js"></script>
</body>
</html>